### CRUD CATEGORIES

### Get all categories
GET http://localhost:3007/api/v1/categories

### Get category by id
GET http://localhost:3007/api/v1/categories/1

### Post Create new category 
POST http://localhost:3007/api/v1/categories 
Content-Type: application/json

{
    "name": "albañilaria"
}

### Patch update category
PATCH http://localhost:3007/api/v1/role/6

{
    "name": "Mascara Tica",
    "category_id": 6,
    "user_id": 1
}

### Delete category

DELETE http://localhost:3007/api/v1/role/7